### ISSUE TITLE
How to Enable Extension after migrate to Isaac Lab

### ISSUE THREAD

**Issue by zoctipus** [isaac-sim/IsaacLabExtensionTemplate#21]
I tried to modify every 'orbit' keywork in this template to 'lab' including extension.toml, It will works fine as standalone project.
then I tried to enable this extension in the Isaac Sim GUI, particular I get the error of :

![Screenshot from 2024-06-10 19-31-41](https://github.com/isaac-orbit/orbit.ext_template/assets/127588710/294fca81-3641-436f-ac18-7f18b414c3c4)

I noticed this repository hasn't been updated for a while especially after major migration to isaac lab has happend.
I am curious how this template's future  plan will be after the orbit migrated to isaac lab. Should I stick to this template?

**Comment by Mayankm96** [comment]
We have now updated the template. Please feel free to open a new issue if you see any problems.
