### ISSUE TITLE
Where shall I put this inside IsaacLab again?

### ISSUE THREAD

**Issue by AK51** [isaac-sim/IsaacLabExtensionTemplate#24]
Hi,

I am still learning IsaacLab, may I know where I shall put your project in Isaaclab?
Is it here? Thx
IsaacLab/source/standalone/workflows

Is there any example youtube video of creating my own robot? Thx

**Comment by zoctipus** [comment]
I think you can put it outside of isaac lab. this template allows you to develop the project using isaac lab as a package instead of modifying isaac lab

**Comment by jih189** [comment]
I made a note for it, but I am still developing.

https://jih189.github.io/isaaclab

Hope it can help

**Comment by Dhoeller19** [comment]
Hi @AK51, this is supposed to be a folder outside of the Isaac Lab repository. It is meant to act as standalone.
