### ISSUE TITLE
How to define a DirectRLEnv

### ISSUE THREAD

**Issue by carlosky66** [isaac-sim/IsaacLabExtensionTemplate#34]
Hi, is there any way to create and register a DirectRLEnv using this template?

**Comment by Dhoeller19** [comment]
Hi @carlosky66, you can simply copy the folder of the direct workflow task you want to use (for example https://github.com/isaac-sim/IsaacLab/tree/main/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/direct/quadcopter) and paste it in the tasks folder https://github.com/isaac-sim/IsaacLabExtensionTemplate/tree/main/exts/ext_template/ext_template/tasks

**Comment by WillMandil001** [comment]
Is there a way to point to this new set of tasks in  /exts/my_templete/my_templete/tasks? I ask as I am getting the error: 
gymnasium.error.NameNotFound: Environment... 
With my newly built task, it works if I copy it into the IsaacLab lab_tasks dir but not in this template? I guess I need to point to this new set of tasks, but how?
