### ISSUE TITLE
Not registering new gym envs

### ISSUE THREAD

**Issue by WillMandil001** [isaac-sim/IsaacLabExtensionTemplate#37]
I have built a task (Isaac-Grasp-Cube-Franka) in IsaacLab and it registers and works/runs fine, but migrating to the externsion template is an issue. 

I get the error: gymnasium.error.NameNotFound: Environment `Isaac-Grasp-Cube-Franka` doesn't exist. Did you mean: `Isaac-Lift-Cube-Franka`?

This is because the extension template is not actually running through the exts/exts_template/exts_template/tasks/

I guess there is a pointer I need to declare or rebuild to make this work?

Has anyone else had this issue and how did you get past it?

**Comment by alessandroassirelli98** [comment]
Hello!
May I ask you how did you solve it?

**Comment by WillMandil001** [comment]
Hey! Yes,

I made a bunch of changes, and im not totally sure which the fix was but I think the key change was:

adjust train.py to import exts/[your_extension_name]/[your_extension_name]/tasks instead of from isaalab:
```python
# import omni.isaac.lab_tasks  # noqa: F401  comment this out
import exts.TRMbench.TRMbench.tasks   # add this
``` 

Let me know if this is not all and I can have a look through my notes.

(FYI I am using sb3 not rsl_rl)

Will

**Comment by alessandroassirelli98** [comment]
Thanks for the quick reply!
Yeah, actually by including that in the scripts it works, but I was wondering if there is a way to not touch the Isaac Lab repo and to not rewrite all the training/dummy scripts of the main repo inside this one
